<?php
/**
 * Bootstrap the plugin unit testing environment.
 *
 * if the env variable PLUGIN_FILE is empty or not exists a file called plugin.php 
 * in the root folder wehere phpunit is launched will be loaded as plugin file
 *
 * This file is autogenerated by WP UnitTest Tools
 */

/**
 * Determine where the WP test suite lives.
 *
 * Support for:
 * 1. `WP_DEVELOP_DIR` environment variable, which points to a checkout
 *   of the develop.svn.wordpress.org repository (this is recommended)
 * 2. `WP_TESTS_DIR` environment variable, which points to a checkout
 * 3. `WP_ROOT_DIR` environment variable, which points to a checkout
 * 4. Plugin installed inside of WordPress.org developer checkout
 * 5. Tests checked out to /tmp
 */
if ( false !== getenv( 'WP_DEVELOP_DIR' ) ) {
	$test_root = getenv( 'WP_DEVELOP_DIR' ) . '/tests/phpunit';
} else if ( false !== getenv( 'WP_TESTS_DIR' ) ) {
	$test_root = getenv( 'WP_TESTS_DIR' );
} else if ( false !== getenv( 'WP_ROOT_DIR' ) ) {
	$test_root = getenv( 'WP_ROOT_DIR' ) . '/tests/phpunit';
} else if ( file_exists( '../../../../tests/phpunit/includes/bootstrap.php' ) ) {
	$test_root = '../../../../tests/phpunit';
} else if ( file_exists( '/tmp/wordpress-tests-lib/includes/bootstrap.php' ) ) {
	$test_root = '/tmp/wordpress-tests-lib';
} else if ( file_exists( './tmp/wordpress-tests-lib/includes/bootstrap.php' ) ) {
	$test_root = './tmp/wordpress-tests-lib';
} else if ( file_exists( '../tmp/wordpress-tests-lib/includes/bootstrap.php' ) ) {
	$test_root = '../tmp/wordpress-tests-lib';
} else if ( file_exists( __DIR__ . '/../tmp/wordpress/includes/bootstrap.php' ) ) {
	$test_root = __DIR__ . '/../tmp/wordpress';
}

if(!isset($test_root) ){
    echo 'Wordpress source not found';
    die();
}

require $test_root . '/includes/functions.php';



function _manually_load_plugin() {
    
    if( false !== getenv( 'PLUGIN_FILE' ) && 'false' !== getenv( 'PLUGIN_FILE' ) && !empty( getenv( 'PLUGIN_FILE' ) ) ){
        require getenv( 'PLUGIN_FILE' );
    }
    else {
        require dirname( __FILE__ ) . '/../plugin.php';
    }
	
}
tests_add_filter( 'muplugins_loaded', '_manually_load_plugin' );

require $test_root . '/includes/bootstrap.php';

